### ISSUE TITLE
Fix Quit Cancel Stop verbiage

### ISSUE THREAD

**Issue by dtzar** [dtzar/AzureBot#77]
If I type "Stop my VM" it cancels the operation based on the keyword stop (it shouldn't do that).  If I type cancel, it doesn't understand (it should quit/cancel the operation).

**Comment by ejadib** [comment]
Quit is something coming out of the box in the FormFlow. We will check if there is away to override the terms used to going out of a form.

**Comment by dtzar** [comment]
You also can't even execute the stop virtual machine commands because it exits. :(

**Comment by f2bo** [comment]
Could it be that the bot was expecting an answer to a question when this happened? 

In this case, the input is handled by the form and you typically need to type the answer. There are also several commands that you can use at this time that will be handled specially including "stop" and "quit", which will cancel the input and return to normal "command mode". Though not "cancel" as you correctly point out.

But it should work otherwise. For example:

![image](https://cloud.githubusercontent.com/assets/1148767/15596848/3cdaedd0-23a1-11e6-9952-c9f2e55154c9.png)

**Comment by dtzar** [comment]
Form flow catch-all for ANY form people are in on how to use it would be great.  Just like you do with the start VM one.
