### ISSUE TITLE
List the current subcription if asked

### ISSUE THREAD

**Issue by dtzar** [dtzar/AzureBot#78]
If you ask "What's my current subscription?" after you've already selected a subscription - the bot just replies and asks which subscription would you like to work with.

**Comment by f2bo** [comment]
The "Show my current subscription" intent is not currently defined in the LUIS model so the closest match is the "Select a subscription" intent. The immediate solution here would be to update the model to understand it and implement a corresponding action in the bot. This would resolve this specific issue.

In more general terms, instead of always using the top match returned by LUIS, we should start looking at the scores and if they are below a certain threshold, reply with a message saying "I didn't understand. Did you mean XXXX?"

**Comment by ejadib** [comment]
@f2bo The specific issue is solved in #85. Can you please add a new enhancement for the thresholds suggestion?
